# Here you can create profile that will contain the data needed for all of your testing,
# That can be MID, MKEYS, credit card, costumer data and so on.
# It's important to note that we should strive to create multiple Profiles that contain the data
# for QA, DEV and PROD (if required), so that the regression can be run in different envs without having to come in and
# rewrite half the automation.
DEV:
  JIRA: REMOVED_COMPANY_DETAILS
  url: REMOVED_COMPANY_DETAILS
  Authorization: REMOVED_COMPANY_DETAILS
  SPSUser: '403652'

QAS:
  JIRA: REMOVED_COMPANY_DETAILS
  url: REMOVED_COMPANY_DETAILS
  Authorization: REMOVED_COMPANY_DETAILS
  SPSUser: '403652'

PROD:
  JIRA: REMOVED_COMPANY_DETAILS